### ISSUE TITLE
key names for plan object

### ISSUE THREAD

**Issue by m59peacemaker** [m59peacemaker/tap-dealio#4]
```
   1..0 # Skipped: WWW::Mechanize not installed
   {start: 1, end: 0, skipAll: true, skipReason: 'Skipped: WWW::Mechanize not installed'}
```

This is the output `tap-parser` produces. Do this or something else?

**Comment by m59peacemaker** [comment]
And is there a principle that says an object produced by a function should always have the same structure?

`{start: 1, end: 5, skipAll: false, skipReason: ''}`
vs
`{start: 1, end: 5}`

**Comment by TehShrike** [comment]
hmm, I don't see skip messages described for plan lines in the spec.  I only see skip messages described for test lines.

I wouldn't expect the lexer to look for skip/todo in test lines - those are just sub-types that the parser would find when looking at test tokens, based on my reading of the spec.

**Comment by m59peacemaker** [comment]
It's there, though in an odd place. Under the "Directives" for a "test", the last part of the section "Skipping tests".

> Similarly, one can include an explanation in a plan line, emitted if the test file is skipped completely:
> 1..0 # Skipped: WWW::Mechanize not installed

**Comment by m59peacemaker** [comment]
See [these tests](https://github.com/m59peacemaker/tap-dealio/blob/master/test/parse.js) for sample input and expected parsing results:

**Comment by m59peacemaker** [comment]
This project is now lexing only. Parsing will be elsewhere.
